#!/usr/bin/env python3
"""
Platform Sync Generator for .deepx/

Generates platform-specific configuration files from the canonical .deepx/
knowledge base. Supports output to:
  - .github/copilot-instructions.md  (GitHub Copilot)
  - .claude/                          (Claude Code / CLAUDE.md)
  - .cursor/rules/                    (Cursor)
  - .vscode/                          (VS Code settings)

Usage:
    python3 generate_platforms.py [--deepx-root DIR] [--output-root DIR]
                                  [--platforms PLATFORM ...]
                                  [--dry-run] [--force]

Exit codes:
    0  All files generated successfully
    1  Generation error
    2  .deepx/ directory not found
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Set


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SUPPORTED_PLATFORMS = ["github", "claude", "cursor", "vscode"]

DEEPX_ROOT_DEFAULT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by .deepx/scripts/generate_platforms.py -->\n"
    "<!-- Do not edit directly. Source of truth: .deepx/ -->\n"
    "<!-- Generated: {timestamp} -->\n\n"
)


# ---------------------------------------------------------------------------
# Knowledge base reader
# ---------------------------------------------------------------------------

class DeepXReader:
    """Read and parse .deepx/ knowledge base files."""

    def __init__(self, deepx_root: str):
        self.root = deepx_root

    def read_file(self, rel_path: str) -> Optional[str]:
        """Read a file relative to .deepx/ root."""
        full = os.path.join(self.root, rel_path)
        if os.path.isfile(full):
            return Path(full).read_text(encoding="utf-8", errors="replace")
        return None

    def list_category(self, category: str) -> List[str]:
        """List files in a category directory."""
        cat_dir = os.path.join(self.root, category)
        if not os.path.isdir(cat_dir):
            return []
        return sorted(f for f in os.listdir(cat_dir)
                       if not f.startswith("."))

    def extract_skills(self) -> List[Dict[str, str]]:
        """Extract skill metadata from skill files."""
        skills = []
        for filename in self.list_category("skills"):
            if not filename.endswith(".md"):
                continue
            content = self.read_file(f"skills/{filename}")
            if not content:
                continue

            # Extract title from first heading
            title_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
            title = title_match.group(1) if title_match else filename

            # Extract description from first paragraph after heading
            desc_match = re.search(
                r'^#\s+.+\n+(?:>.*\n+)*(.+?)(?:\n\n|\n#)',
                content, re.MULTILINE
            )
            desc = desc_match.group(1).strip() if desc_match else ""

            # Derive command name
            command = "/" + filename.replace(".md", "")

            skills.append({
                "command": command,
                "title": title,
                "description": desc,
                "filename": filename,
            })
        return skills

    def extract_elements_summary(self) -> List[Dict[str, str]]:
        """Extract element summary from dx-stream-elements.md."""
        content = self.read_file("toolsets/dx-stream-elements.md")
        if not content:
            return []

        elements = []
        # Match ## N. ElementName patterns
        pattern = re.compile(
            r'^##\s+\d+\.\s+(\w+)\s*\n+\*\*Description:\*\*\s*(.+?)(?:\n\n|\n\*\*)',
            re.MULTILINE | re.DOTALL
        )
        for match in pattern.finditer(content):
            elements.append({
                "name": match.group(1),
                "description": match.group(2).strip().split("\n")[0],
            })
        return elements

    def extract_routing_table(self) -> List[Dict[str, str]]:
        """Extract context routing table entries."""
        # Build from known structure
        return [
            {
                "trigger": "Pipeline, detection, classification",
                "files": ".deepx/skills/dx-build-pipeline-app.md, "
                         ".deepx/toolsets/dx-stream-elements.md",
            },
            {
                "trigger": "MQTT, Kafka, message broker",
                "files": ".deepx/skills/dx-build-mqtt-kafka-app.md, "
                         ".deepx/toolsets/dx-stream-elements.md",
            },
            {
                "trigger": "Multi-model, cascaded, tiled",
                "files": ".deepx/skills/dx-build-pipeline-app.md, "
                         ".deepx/toolsets/dx-stream-metadata.md",
            },
            {
                "trigger": "Model, download",
                "files": ".deepx/skills/dx-model-management.md",
            },
            {
                "trigger": "Validation, testing",
                "files": ".deepx/skills/dx-validate.md, "
                         ".deepx/instructions/testing-patterns.md",
            },
            {
                "trigger": "ALWAYS read (every task)",
                "files": ".deepx/memory/common_pitfalls.md, "
                         ".deepx/instructions/coding-standards.md",
            },
        ]

    def extract_conventions(self) -> List[str]:
        """Extract critical conventions from coding-standards.md."""
        content = self.read_file("instructions/coding-standards.md")
        if not content:
            return []

        conventions = []
        # Extract numbered section titles
        pattern = re.compile(r'^###\s+\d+\.\s+(.+)$', re.MULTILINE)
        for match in pattern.finditer(content):
            conventions.append(match.group(1).strip())
        return conventions

    def extract_pitfalls(self) -> List[Dict[str, str]]:
        """Extract pitfall summaries from common_pitfalls.md."""
        content = self.read_file("memory/common_pitfalls.md")
        if not content:
            return []

        pitfalls = []
        pattern = re.compile(
            r'^##\s+\d+\.\s+\[(\w+)\]\s+(.+?)$\n+'
            r'\*\*Symptom:\*\*\s*(.+?)$',
            re.MULTILINE
        )
        for match in pattern.finditer(content):
            pitfalls.append({
                "tag": match.group(1),
                "title": match.group(2).strip(),
                "symptom": match.group(3).strip(),
            })
        return pitfalls


# ---------------------------------------------------------------------------
# GitHub Copilot generator
# ---------------------------------------------------------------------------

def generate_github_copilot(reader: DeepXReader) -> str:
    """Generate .github/copilot-instructions.md."""
    # Read template if available
    template = reader.read_file("templates/copilot-instructions.md")
    if template:
        # Perform template substitutions
        output = template

        # {ROUTING_TABLE}
        routing = reader.extract_routing_table()
        table_rows = []
        for entry in routing:
            table_rows.append(
                f"| **{entry['trigger']}** | {entry['files']} |"
            )
        routing_table = (
            "| If the task mentions... | Read these files |\n"
            "|---|---|\n" +
            "\n".join(table_rows)
        )
        output = output.replace("{ROUTING_TABLE}", routing_table)

        # {SKILLS_TABLE}
        skills = reader.extract_skills()
        skill_rows = []
        for s in skills:
            skill_rows.append(f"| `{s['command']}` | {s['description']} |")
        skills_table = (
            "| Command | Description |\n"
            "|---------|-------------|\n" +
            "\n".join(skill_rows)
        )
        output = output.replace("{SKILLS_TABLE}", skills_table)

        # {ELEMENTS_TABLE}
        elements = reader.extract_elements_summary()
        elem_rows = []
        for e in elements:
            elem_rows.append(f"| `{e['name']}` | {e['description']} |")
        elements_table = (
            "| Element | Purpose |\n"
            "|---------|--------|\n" +
            "\n".join(elem_rows)
        )
        output = output.replace("{ELEMENTS_TABLE}", elements_table)

        # {CONVENTIONS_LIST}
        conventions = reader.extract_conventions()
        conv_list = "\n".join(f"{i+1}. **{c}**" for i, c in enumerate(conventions))
        output = output.replace("{CONVENTIONS_LIST}", conv_list)

        # {PITFALLS_LIST}
        pitfalls = reader.extract_pitfalls()
        pit_list = "\n".join(
            f"- **[{p['tag']}] {p['title']}**: {p['symptom']}"
            for p in pitfalls
        )
        output = output.replace("{PITFALLS_LIST}", pit_list)

        return output

    # Fallback: generate from scratch
    return _generate_copilot_from_scratch(reader)


def _generate_copilot_from_scratch(reader: DeepXReader) -> str:
    """Generate copilot instructions without template."""
    lines = [
        "# dx_stream — GitHub Copilot Instructions\n",
        "> GStreamer-based video analytics framework for DEEPX NPU.\n",
        "## Context Routing Table\n",
    ]

    routing = reader.extract_routing_table()
    lines.append("| If the task mentions... | Read these files |")
    lines.append("|---|---|")
    for entry in routing:
        lines.append(f"| **{entry['trigger']}** | {entry['files']} |")

    lines.append("\n## Skills\n")
    skills = reader.extract_skills()
    lines.append("| Command | Description |")
    lines.append("|---------|-------------|")
    for s in skills:
        lines.append(f"| `{s['command']}` | {s['description']} |")

    lines.append("\n## 13 GStreamer Elements\n")
    elements = reader.extract_elements_summary()
    lines.append("| Element | Purpose |")
    lines.append("|---------|---------|")
    for e in elements:
        lines.append(f"| `{e['name']}` | {e['description']} |")

    lines.append("\n## Critical Conventions\n")
    conventions = reader.extract_conventions()
    for i, c in enumerate(conventions):
        lines.append(f"{i+1}. **{c}**")

    lines.append("\n## Common Pitfalls\n")
    pitfalls = reader.extract_pitfalls()
    for p in pitfalls:
        lines.append(f"- **[{p['tag']}] {p['title']}**: {p['symptom']}")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Claude Code generator
# ---------------------------------------------------------------------------

def generate_claude(reader: DeepXReader) -> Dict[str, str]:
    """Generate CLAUDE.md entry point."""
    files = {}

    lines = [
        "# dx_stream — Claude Code Entry Point\n",
        "> Self-contained entry point for dx_stream GStreamer pipeline "
        "development.\n",
        "## Shared Knowledge\n",
        "All skills, instructions, toolsets, and memory live in `.deepx/`.",
        "Read `.deepx/README.md` for the complete index.\n",
        "## Quick Reference\n",
        "```bash",
        "./install.sh                        # Install GStreamer plugin bindings",
        "./setup.sh                          # Download sample models and videos",
        "dxrt-cli -s                         # Verify NPU availability",
        "gst-inspect-1.0 dxinfer             # Verify DxInfer plugin is registered",
        'pytest test/ -m "not npu_required"  # Run unit tests (no NPU)',
        "pytest test/ -m npu_required        # Run NPU integration tests",
        "```\n",
        "## Skills\n",
    ]

    skills = reader.extract_skills()
    lines.append("| Command | Description |")
    lines.append("|---------|-------------|")
    for s in skills:
        lines.append(f"| {s['command']} | {s['description']} |")

    lines.append("\n## Critical Conventions\n")
    conventions = reader.extract_conventions()
    for i, c in enumerate(conventions):
        lines.append(f"{i+1}. **{c}**")
    # Add standard conventions
    lines.extend([
        f"{len(conventions)+1}. **Logging**: `logging.getLogger(__name__)` — "
        "no bare `print()`",
        f"{len(conventions)+2}. **Skill doc is sufficient**: Do NOT read "
        "source code unless skill is insufficient",
        f"{len(conventions)+3}. **No hardcoded model paths**: Use variables "
        "or config for model path resolution",
    ])

    lines.append("\n## Context Routing Table\n")
    routing = reader.extract_routing_table()
    lines.append("| Task mentions... | Read these files |")
    lines.append("|---|---|")
    for entry in routing:
        lines.append(f"| **{entry['trigger']}** | {entry['files']} |")

    lines.append("\n## 13 GStreamer Elements\n")
    elements = reader.extract_elements_summary()
    lines.append("| Element | Purpose |")
    lines.append("|---------|---------|")
    for e in elements:
        lines.append(f"| `{e['name']}` | {e['description']} |")

    lines.append("\n## Hardware\n")
    lines.append("| Architecture | Value |")
    lines.append("|---|---|")
    lines.append("| DX-M1 | `dx_m1` |")
    lines.append("| DX-M1A | `dx_m1a` |")

    lines.append("\n## Memory\n")
    lines.append("Persistent knowledge in `.deepx/memory/`. Read at task "
                 "start, update when learning.")

    files["CLAUDE.md"] = "\n".join(lines) + "\n"
    return files


# ---------------------------------------------------------------------------
# Cursor generator
# ---------------------------------------------------------------------------

def generate_cursor(reader: DeepXReader) -> Dict[str, str]:
    """Generate .cursor/rules/ files."""
    files = {}

    # Main rules file
    lines = [
        "# dx_stream Development Rules\n",
        "## Pipeline Conventions\n",
    ]

    conventions = reader.extract_conventions()
    for i, c in enumerate(conventions):
        lines.append(f"{i+1}. {c}")

    lines.append("\n## Element Reference\n")
    elements = reader.extract_elements_summary()
    for e in elements:
        lines.append(f"- **{e['name']}**: {e['description']}")

    lines.append("\n## Common Pitfalls\n")
    pitfalls = reader.extract_pitfalls()
    for p in pitfalls:
        lines.append(f"- [{p['tag']}] {p['title']}")

    files[".cursor/rules/dx-stream.md"] = "\n".join(lines) + "\n"
    return files


# ---------------------------------------------------------------------------
# VS Code generator
# ---------------------------------------------------------------------------

def generate_vscode(reader: DeepXReader) -> Dict[str, str]:
    """Generate .vscode/ configuration files."""
    files = {}

    # settings.json with dx_stream-specific settings
    settings = {
        "files.associations": {
            "*.dxnn": "binary",
            "meson.build": "meson",
        },
        "files.exclude": {
            "**/__pycache__": True,
            "**/*.pyc": True,
            "**/builddir": True,
        },
        "python.analysis.extraPaths": [
            "${workspaceFolder}/bindings/python",
        ],
        "search.exclude": {
            "**/builddir": True,
            "**/samples/models": True,
            "**/samples/videos": True,
        },
    }

    files[".vscode/settings.json"] = json.dumps(settings, indent=4) + "\n"

    # tasks.json for common dx_stream operations
    tasks = {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "dx_stream: Build postprocess libraries",
                "type": "shell",
                "command": "./build.sh",
                "group": "build",
            },
            {
                "label": "dx_stream: Install GStreamer plugin",
                "type": "shell",
                "command": "./install.sh",
                "group": "build",
            },
            {
                "label": "dx_stream: Download models",
                "type": "shell",
                "command": "./setup.sh",
            },
            {
                "label": "dx_stream: Check NPU",
                "type": "shell",
                "command": "dxrt-cli -s",
            },
            {
                "label": "dx_stream: Validate pipeline app",
                "type": "shell",
                "command": "python3 .deepx/scripts/validate_app.py "
                           "${input:scriptPath}",
            },
            {
                "label": "dx_stream: Run tests (no NPU)",
                "type": "shell",
                "command": "pytest test/ -m 'not npu_required' -v",
                "group": "test",
            },
        ],
        "inputs": [
            {
                "id": "scriptPath",
                "description": "Pipeline script path",
                "type": "promptString",
                "default": "dx_stream/pipelines/",
            },
        ],
    }

    files[".vscode/tasks.json"] = json.dumps(tasks, indent=4) + "\n"

    return files


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

GENERATORS = {
    "github": lambda r: {".github/copilot-instructions.md":
                          generate_github_copilot(r)},
    "claude": generate_claude,
    "cursor": generate_cursor,
    "vscode": generate_vscode,
}


def generate(deepx_root: str, output_root: str,
             platforms: List[str], dry_run: bool = False,
             force: bool = False) -> int:
    """Generate platform files from .deepx/ knowledge base."""
    reader = DeepXReader(deepx_root)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    errors = 0

    for platform in platforms:
        if platform not in GENERATORS:
            print(f"[ERROR] Unknown platform: {platform}")
            errors += 1
            continue

        print(f"\n--- Generating: {platform} ---")
        generator = GENERATORS[platform]
        try:
            files = generator(reader)
        except Exception as e:
            print(f"[ERROR] Generator failed for {platform}: {e}")
            errors += 1
            continue

        for rel_path, content in files.items():
            full_path = os.path.join(output_root, rel_path)

            # Check for existing file
            if os.path.isfile(full_path) and not force:
                # Check if it was auto-generated
                try:
                    existing = Path(full_path).read_text(
                        encoding="utf-8", errors="replace"
                    )
                    if "AUTO-GENERATED by .deepx/" not in existing:
                        print(f"  [SKIP] {rel_path} (manually edited, "
                              f"use --force to overwrite)")
                        continue
                except Exception:
                    pass

            # Add generated header for markdown files
            if rel_path.endswith(".md"):
                content = GENERATED_HEADER.format(timestamp=timestamp) + content

            if dry_run:
                print(f"  [DRY-RUN] Would write: {rel_path} "
                      f"({len(content)} bytes)")
            else:
                # Create directory if needed
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                Path(full_path).write_text(content, encoding="utf-8")
                print(f"  [WROTE] {rel_path} ({len(content)} bytes)")

    return errors


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate platform configs from .deepx/ knowledge base"
    )
    parser.add_argument(
        "--deepx-root",
        default=DEEPX_ROOT_DEFAULT,
        help="Path to .deepx/ directory (default: auto-detect)"
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help="Output root directory (default: parent of .deepx/)"
    )
    parser.add_argument(
        "--platforms", nargs="+",
        default=SUPPORTED_PLATFORMS,
        choices=SUPPORTED_PLATFORMS,
        help="Platforms to generate for (default: all)"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be generated without writing files"
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite manually-edited files"
    )
    parser.add_argument(
        "--list-platforms", action="store_true",
        help="List supported platforms and exit"
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if args.list_platforms:
        print("Supported platforms:")
        for p in SUPPORTED_PLATFORMS:
            print(f"  - {p}")
        sys.exit(0)

    deepx_root = args.deepx_root
    if not os.path.isdir(deepx_root):
        print(f"[ERROR] .deepx/ directory not found: {deepx_root}")
        sys.exit(2)

    # Default output root is the parent of .deepx/
    output_root = args.output_root
    if output_root is None:
        output_root = os.path.dirname(deepx_root)

    print(f"Source:  {deepx_root}")
    print(f"Output:  {output_root}")
    print(f"Platforms: {', '.join(args.platforms)}")

    errors = generate(
        deepx_root=deepx_root,
        output_root=output_root,
        platforms=args.platforms,
        dry_run=args.dry_run,
        force=args.force,
    )

    if errors:
        print(f"\n[DONE] Completed with {errors} error(s)")
        sys.exit(1)
    else:
        print("\n[DONE] All platforms generated successfully")
        sys.exit(0)


if __name__ == "__main__":
    main()
